# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: https://shenghungkuan.github.io

# Title of the Site
title: Sheng-Hung Kuan
# Description of the Site
description: Software Engineer
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Software engineer, Intern
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: marcuskuan0329@gmail.com
facebook_username: /
twitter_username: /
instagram_username: /
linkedin_username: shenghungkuan
github_username:  shenghungKuan
youtube_channel_id: /
reddit_username: /
behance_username: /
dribbble_username: /
spotify_username: /

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: Sheng-Hung Kuan

# Name of the Author
author-name: Sheng-Hung Kuan
# URL for the Image of the Author
author-image: ./assets/images/profile_pic.jpg
# 60 Words About the Author
author-about: Welcome to my portfolio! I'm Sheng-Hung (Marcus), a dedicated Master's student specializing in Computer Science. With a robust academic background encompassing data structures, algorithms, object-oriented programming, system foundations, machine learning, web development, and artificial intelligence, I bring a comprehensive skill set to tackling diverse challenges with confidence along with my practical experience spans across Python, Java, C/C++, JavaScript, HTML, and CSS, proficient in essential tools, including GitHub for version control, Docker for containerization, and MySQL for data management. I am passionate about collaborating with professionals, mentors, and organizations with my problem-solving, teamwork, and communication skills. Whether refining existing solutions or spearheading new initiatives, I am committed to driving impactful outcomes through collaboration and ingenuity.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/shenghungKuan

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
